# Generated by Django 4.1.3 on 2022-12-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Description',
            new_name='description',
        ),
    ]
